### ISSUE TITLE
Feature Request: Can there be a more detailed explanation? 

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [Quorafind/Obsidian-Link-Nodes-In-Canvas#3]
### Feature Requested

Can there be a more detailed explanation? 

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
1. Select file nodes in canvas.
2. If those nodes linked, create edges between them.

**Comment by steveylang** [comment]
That helps, thanks! (I couldn't quite tell from the showcase example.)

> * Select file nodes in canvas.
> * If those nodes linked, create edges between them.

**Comment by YAMLcase** [comment]
@shoudeyunkaijianyueming thanks for asking about this.  I too was confused about what this does and didn't know why it wasn't working.

**Comment by badjerphoenix** [comment]
I am still confused as to what this plug in is supposed to do & am uncertain what is even being referred to as to the "edge". The other canvas plug ins that you have developed are quite powerful (found them the other day by accident) & am now wondering what this plug in is offering to canvas

I have watched the short demo & cannot grasp what is happening. The brief description seems a little too vague for me. When I install it I do not notice anything happening

Any help would be appreciated
Thanks

**Comment by sjoshua270** [comment]
I learned how to do it! You need to make sure the plugin is enabled first, just under the Community Plugins area. Next, you can search for the command using Ctrl/Cmd + P
Run the command while items on your canvas are selected.

**Comment by steveylang** [comment]
> I am still confused as to what this plug in is supposed to do & am uncertain what is even being referred to as to the "edge". What I thought it was supposed to do was to quickly connect the cards I have selected via the hotkey/ command palette. Vs having to manually connect them 1 by 1. However, nothing happens when I do this so I presume I have misunderstood the intended behaviour of the plug in
> 
> I have watched the short demo & cannot figure out what is supposed to be happening beyond what I have listed above. When I install it I do not notice anything either
> 
> Any help would be appreciated Thanks

The plugin will only create links between cards if the card contents have links between them. What you would like might also be useful, but I'm not sure how often you want to select a bunch of cards have all of them linked to each other. This command uses the note content to determine if a link should be made.

Right now though I am not able to actually use the plugin, it always tells me "You should have at least one edge in the canvas to use this command" even though I have multiple notes selected. There is another request posted reporting this bug.

**Comment by Quorafind** [comment]
Don't need to add at least one edge any more. You can just select file's card(they have been linked to each other); and then run commands or just link any file card to other file cards.
