### ISSUE TITLE
Feature Request: supporting creating links in note by the line draw between cards on canvas

### ISSUE THREAD

**Issue by Ravenclawer** [Quorafind/Obsidian-Link-Nodes-In-Canvas#4]
### Feature Requested

supporting creating links in note by the line draw between cards on canvas

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
I don't know what you mean, do you mean that you want to generate bi-link when create a new edge between different node?

**Comment by Ravenclawer** [comment]
yes exactly

**Comment by Quorafind** [comment]
Available in latest version.
