### ISSUE TITLE
[Bug]: I don't know what it means by edge

### ISSUE THREAD

**Issue by DannyHatcher-Git** [Quorafind/Obsidian-Link-Nodes-In-Canvas#6]
### Bug Description

This is the error I get.
![image](https://user-images.githubusercontent.com/78496825/213478850-b26ee24b-24d5-416a-9291-916e8167fef5.png)

How do I solve this?

### Obsidian Version

1,1.12

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by firefoxic** [comment]
I have the same issue.

**Comment by bpriyum** [comment]
Same issue here.

**Comment by badjerphoenix** [comment]
Was also wondering what is meant by "edge". Thanks for asking this question - was going to ask same thing

**Comment by steveylang** [comment]
I think I figured out the problem. Once you have a link anywhere on the canvas, the plugin seems to work as designed. The link doesn't even have to be in the group of cards you've selected to run this command on. So you can just create a random link between 2 blank cards even, then run the command on your actual content and it will work.

This bug can probably be corrected easily, but for now this is an easy workaround if you want to use this plugin. It is a very nice ability to have with canvases!

**Comment by Quorafind** [comment]
That means you need to have at least one edge(a line between two cards) in current canvas.
