### ISSUE TITLE
[Bug]: Add duplicate edges

### ISSUE THREAD

**Issue by wenbopeng** [Quorafind/Obsidian-Link-Nodes-In-Canvas#8]
### Bug Description

If I run the command multiple times, it adds a lot of duplicate edges

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/74350447/223041913-bf524f3b-2718-4221-a01f-e0f4a3cffd3c.png)

### To Reproduce

1. Add any edge;
2. Run `Link Nodes In Canvas:Link Between Selection Nodes` many times;

### Obsidian Version

1.1.16

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by igorlvicente** [comment]
I can confirm this bug on version 0.0.5 and Obsidian version 1.4.16

**Comment by Quorafind** [comment]
Got fixed.
